# Generated by Django 5.1.4 on 2025-01-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_remove_feed_profile_image_remove_feed_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="nickname",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="feed",
            name="profile_image",
            field=models.TextField(default=""),
        ),
    ]
