# Generated by Django 5.1.4 on 2025-01-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_feed_nickname_feed_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
