# Generated by Django 5.1.4 on 2025-01-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_feed_like_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="nickname",
        ),
        migrations.RemoveField(
            model_name="feed",
            name="profile_image",
        ),
    ]
