# Generated by Django 5.1.4 on 2025-01-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_remove_feed_nickname_remove_feed_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_id", models.IntegerField(default=0)),
                ("email", models.EmailField(default="", max_length=254)),
                ("is_marked", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_id", models.IntegerField(default=0)),
                ("email", models.EmailField(default="", max_length=254)),
                ("is_like", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_id", models.IntegerField(default=0)),
                ("email", models.EmailField(default="", max_length=254)),
                ("reply_content", models.TextField()),
            ],
        ),
    ]
