# Generated by Django 5.1.4 on 2025-01-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_bookmark_like_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="like_count",
        ),
    ]
